DROP TABLE user_roles IF EXISTS;
DROP TABLE users IF EXISTS;
DROP TABLE dishes IF EXISTS;
DROP TABLE restaurants IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE restaurants
(
  id              INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name            VARCHAR(255)      NOT NULL,
  address         VARCHAR(255)      NOT NULL,
  rating          INTEGER DEFAULT 0
);
CREATE UNIQUE INDEX restaurants_unique_name_idx ON restaurants(name);

CREATE TABLE dishes
(
  id              INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name            VARCHAR(255),
  price           DECIMAL(10, 2),
  restaurant_id   INTEGER NOT NULL,
  FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX dishes_unique_restaurant_idx ON dishes(restaurant_id,name);

CREATE TABLE users
(
  id              INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name            VARCHAR(255)      NOT NULL,
  email           VARCHAR(255)      NOT NULL,
  password        VARCHAR(255)      NOT NULL,
  registered      TIMESTAMP DEFAULT now(),
  enabled         BOOLEAN DEFAULT TRUE,
  restaurant_id   INTEGER,
  FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX users_unique_email_idx ON users(email);

CREATE TABLE user_roles
(
  user_id         INTEGER NOT NULL,
  role            VARCHAR(255),
  CONSTRAINT user_roles_idx UNIQUE (user_id,role),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
